name: Update Development

on:
    push:
        branches: '**-beta'

jobs:
    update-development:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: SSH into server and deploy 
              uses: appleboy/ssh-action@v0.1.9
              if: contains(github.event.head_commit.message, '[debug]')
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 22
                  script: |
                    cd /home/cpplus/betaclient
                    git checkout ${{ github.ref_name }}
                    git pull --recurse-submodules
                    npm install
                    npm run build-dev
              
            - name: SSH into server and deploy
              uses: appleboy/ssh-action@v0.1.9
              if: (!contains(github.event.head_commit.message, '[debug]'))
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  port: 22
                  script: |
                    cd /home/cpplus/betaclient
                    git checkout ${{ github.ref_name }}
                    git pull --recurse-submodules
                    npm install
                    npm run build